_GPL.j(function(e,d,hb,C,n,v,na,r,oa,Ia,G,Kb,Lb,Mb,pa,N,f,ib,qa,jb,A,x,kc,y,Nb,Ja){function Ka(a,b,c){c=c||f;var d=!0;a&&e.each(a,function(g,e){return d=!!b.call(c,e,g,a)});return d}function Ob(a){var b=[];Ka(a,function(a){0>e.inArray(a,b,void 0)&&b.push(a);return!0});return b}function La(){}function Pb(a,b){return e(a).parents().is(b)}function Qb(a){return e(a).map(function(a,c){(a=c.parentNode)&&a.removeChild(c);return c}).toArray()}function Ma(a,b){function c(b){for(var c=a.split(".");b&&c.length;)b=
b[c.shift()];return b}if(a)return Pb(ra,k.body)||(ra=Qb('<iframe style="display:none;visibility:hidden"></iframe>')[0],k.body.appendChild(ra)),c(ra.contentWindow)||b||c(f)}function Na(a){var b=(a=a||f.event)&&a.type;if(b&&(a.cancelBubble=!0,Ma("Event.prototype.stopImmediatePropagation",La).call(a),Ma("Event.prototype.stopPropagation",La).call(a),"beforeunload"!==b))return a.returnValue=!1,Ma("Event.prototype.preventDefault",La).call(a),!b}function V(a){a=Ia.userAgent.match(Kb(a+"[/ ](\\d+)","i"));
return(a&&a[1])|0}function Rb(a,b,c,d){var g=[];Ka(a,function(c,e){var f=b.call(this,c,e,a);(f!==N||d)&&g.push(f);return!0},c||f);return g}function Sb(a){a&&"object"===typeof a&&(a=e.extend.apply(e,arguments));return a}function u(a){var b={_:1E8*Math.random()|0},c="cdnstats-a.akamaihd.net/s.gif?";Ka(arguments,function(a){"string"===typeof a?c=a:Sb(b,"function"===typeof a?a(b):a);return!0});(new Image).src=r.protocol+"//"+c+Rb(b,function(a,b){if(null!==a&&a!==N)return v(pa(b))+"="+v(pa(a))}).join("&")}
function Tb(a,b){b=b||[];for(var c=0,d=Math.random(),g,e=0;e<b.length;e++)if(c+=b[e][1],d<c&&!g&&(g=b[e][0]),b[e][0]===a){g=a;break}return g||b[0][0]}function H(){return new n/1E3|0}function Oa(a,b,c){function d(a,b,c){try{return Object.defineProperty(a,b,c),!0}catch(lc){return!1}}function g(a,b,c){try{if(Object.prototype.__defineGetter__)return"value"in c?a.__defineGetter__(b,function(){return c.value}):("get"in c&&a.__defineGetter__(b,c.get),"set"in c&&a.__defineSetter__(b,c.set)),!0;if("value"in
c)return a[b]=c.value,!0}catch(d){}return!1}if(!sa)try{d({},"x",{}),sa=d}catch(e){sa=g}return sa(a,b,c)}function Ub(){if("1797"===p&&"GB"===l||f.name.match(/^_odctxdsp/)||"facebook.com"===O)return!1;if(kb)return u({t:"idlecrawler",d:d.gd(),xr:+m,cid:l,pid:p,guid:d.guid}),!1;m?(P=ea=0,Q=180,A+="_xr",x+="_xr",y+="_xr"):(ea=60,P=7,Q=60);fa();return!0}function fa(){ga(k,qa,fa);Pa&&!h?W(!0):Vb(function(a,b,c){ta=a;Qa=b;X||(X=!0,Ra=!1,Wb(),Xb(),Sa(),e('<link rel="dns-prefetch" href="//'+ua+'">').appendTo(k.getElementsByTagName("head")[0]||
R),c&&e('<link rel="dns-prefetch" href="//'+c+'">').appendTo(k.getElementsByTagName("head")[0]||R),va=+new n,wa=e(f).scrollLeft(),xa=e(f).scrollTop(),t(k,qa,lb),t(f,"scroll",mb),t(f,"unload",nb),ob=Yb(function(){36E5<+new n-va&&(u({t:"p_inactive",d:d.gd(),xr:+m,cid:l,pid:p,guid:d.guid,bf:h|0}),W(!1))},5E3))})}function Wb(){function a(a){var c=pb();B.attr({href:c,target:Ta()}).prop("src",c+"&"+d.B64.decode("ZGlzY2xvc2U="));return Na(a)}B||(B=e('<a style="z-index:999999999999999;padding:0;margin:0;cursor:default;opacity:0.01;position:fixed;top:0;left:0;background:transparent;width:100%;height:100%;">&nbsp;</a>'),
t(B[0],"mousedown",a),t(B[0],"mouseup",Na),t(B[0],"click",q),a());ya()}function lb(a){ha=[a.pageX,a.pageY,wa,xa];va=+new n;ya()}function mb(){wa=e(f).scrollLeft();xa=e(f).scrollTop();va=+new n;ya()}function W(a){X&&(X=!1,hb(ob),C(Ua),B.remove(),Zb(),ga(k,qa,lb),ga(k,"scroll",mb),ga(f,"unload",nb),Qa=ta=N,S=T="",a||t(k,qa,fa))}function t(a,b,c){if(f[ib]){var d=za();try{return d.call(a,b,c,!0)}catch(g){a[ib](b,c,!0)}}else a.attachEvent("on"+b,c)}function Xb(){ia=!0;d.ah(E,q);Y||d.ah("keydown",q);d.ah("focus",
q);Y&&d.ah("blur",q);try{var a=k.createElement("iframe");a.style.width="0px";a.style.height="0px";a.style.border="none";k.body.appendChild(a);a.contentWindow.focus();f.focus();k.body.removeChild(a)}catch(b){}Va&&d.ah("keyup",q);e("*").add(f).each(function(a,c){Aa(c)||t(c,E,q)});qb||(qb=!0,e("*").add(f).each(function(a,c){Aa(c)||(t(c,"mousedown",U),t(c,"mouseup",U),t(c,"click",U))}),d.ah&&(d.ah("mousedown",U),d.ah("mouseup",U),d.ah("click",U)));e("iframe").each(function(a,c){try{Aa(c)||t(c.contentWindow,
E,q)}catch(d){}})}function $b(){if(V("Chrome")){for(var a=0;a<Ia.plugins.length;a++)if("Widevine Content Decryption Module"===Ia.plugins[a].name)return!1;return!0}return!1}function ya(){if(X){B.is(R.lastChild)||B.appendTo(k.body);B.css({"z-index":999999999999999,padding:0,margin:0,cursor:"default",opacity:.01,position:"fixed",top:0,left:0,background:"transparent",width:"100%",height:"100%"});50<new n-rb&&(rb=+new n,sb=e("*").filter(function(a,c){return c[tb]}));var a=!1;e.each(sb,function(b,c){return!(a=
ub(c))});B.css("display",a?"none":"block");C(Ua);Ua=I(ya,50)}}function ub(a){a=e(a);var b=ha[0]+(wa-ha[2]),c=ha[1]+(xa-ha[3]),d=a.offset(),g=d.left,d=d.top;return b>=g&&b<=g+a.width()&&c>=d&&c<=d+a.height()}function ac(a,b,c){function d(a,b){C(Wa);Wa=I(function(){g&&!g.closed&&(f.onbeforeunload=function(){},f.name=b,e("iframe").not('[src="https://cdncache-a.akamaihd.net/store/"]').remove(),r.href=a)},300)}if(!J&&!Xa){Z.parentNode&&ja||(ja=Ya());b!==r.href&&c&&(d(b,a),b=r.href,a="_blank",J=!0);var g;
Xa=!0;if(V("Edge"))g=ja(b,a);else if(g=ja("","1749"===p?a:"_blank"))"_blank"!==a&&(g.name=a),g.location.href=b;Xa=!1;!c||g&&!g.closed||(J=!1,C(Wa),Y&&(ja=Ya()));return g}}function Ta(){var a="ld893_";T&&(a+="_"+v(T),S&&(a+=","+S),a+="_");return a+="_"+H()}function pb(){if(ta){var a=ta;h&&!ka&&(a+="&bf=1&fo=1");var b;e("a[href]").not(B).each(function(a,d){ub(d)&&d.protocol.match(/^http/i)&&-1===d.href.indexOf(vb)&&-1===d.href.indexOf(ua)&&(b=d.protocol+"//"+d.host+d.pathname+d.search+d.hash)});b&&
(a+="&t="+v(b.substring(0,oa(0,1500-a.length))));a+="&rt="+(+new n-wb);Ba&&(a+="&data_tag="+v(Ba));return a+=xb?"&data_sid="+v(xb):""}}function bc(){var a=[];e("title").length&&(a=a.concat(e("title").text().toLowerCase().replace(/[.,!?]/g," ").split(" ")));e('meta[property="og:title"],meta[property="og:description"],meta[name="description"],meta[name="keywords"]').each(function(){var b=e.trim(e(this).attr("content"));b&&b.match(/^\s*[a-zA-Z0-9]/)&&(a=a.concat(b.toLowerCase().replace(/[.,!?]/g," ").split(" ")))});
a=e.trim(Ob(a).join(",").replace(/([,]+)/g,",").replace(/\s+/g," ")).split(",");return e.unique(a).join(",")}function Ca(a,b,c){a=(a||r.href).substr(0,1500);var e=c!==N?c:bc();a=a.replace(/:/g,"%3A");e=e.replace(/:/g,"%3A").substring(0,oa(0,1500-a.length));c=d.getSubId?"&subid="+d.getSubId(la):"";a=v(d.B64.encode(a+"::z-"+p+"-"+Za+"::"+e));b="&cb="+(b||yb);b+="&data_fr="+(zb(K)?"false":"true");b+="&data_proto="+v(r.protocol);b+="&ed=1";h&&(b+="&bf=1&fo=1&data_bf=1&data_fo=1");return d.proto+vb+"/pops?c="+
a+"&a=1&ch="+v(Da)+c+b}function ga(a,b,c){if(f[jb])a[jb](b,c,!0);else a.detachEvent("on"+b,c)}function Zb(){ia=!1;d.rh(E,q);Y||d.rh("keydown",q);d.rh("focus",q);Y&&d.rh("blur",q);Va&&d.rh("keyup",q);e("*").add(f).off(E,q);e("iframe").each(function(a,b){try{e(b.contentWindow).off(E,q)}catch(c){}});hb(cc)}function dc(a){a=a||f.event||{};if(J)return!0;for(a=a.target||a.srcElement;a;){var b=Aa(a);if(b)return Ra||(u({t:"p_bo",d:d.gd(),xr:+m,cid:l,pid:p,guid:d.guid,reason:b,bf:h|0}),Ra=!0),!0;a=a.parentNode}return!1}
function F(a,b){a=G(a,10);isNaN(a)&&(a=G(na&&na.getItem(b)||d.gc(b,10),10)||0);return a}function zb(a){return(new n(1E3*(a||0))).toDateString()===(new n).toDateString()}function Ea(){K|=0;w|=0;aa|=0;var a=H(),b=w&&!zb(K);b&&(w=0,z.set(y,w));var c=!P||a-K>=ea&&w<P,a=a-aa>=Q;return!m&&b||c&&a}function q(a){a=a||f.event||{};if(!dc(a)){var b=-1<["mousedown","mouseup","click"].indexOf(a.type);if(!(-1<["keydown","keyup"].indexOf(a.type)&&a.metaKey)){var c,e=ia&&Ab(),g=pb();e&&(d.log("Popping to: "+g),c=
ac(Ta(),g,b));if(c&&!c.closed)return J=!0,e={url:g,cid:T,crid:S},W(!0),Bb(),u({t:"p_success",d:d.gd(),xr:+m,cid:l,pid:p,guid:d.guid,bf:h|0}),Fa&&C(Fa),Ga&&C(Ga),ec(c,e),b||ma(),U(a);c&&c.closed?Ga||(Ga=I(function(){u({t:"popclose",u:g,location:r.hostname,pid:p,guid:d.guid,tag:Ba||"",bf:h|0})},1E3)):e?Fa||(Fa=I(function(){u({t:"popfail",e:a.type,u:g,location:r.hostname,pid:p,guid:d.guid,tag:Ba||""})},1E3)):ma()}}}function ec(a,b){function c(){ga(f,"focus",c);var a=+new n-g;u({delay:a,t:"pop_f",cid:b.cid,
crid:b.crid,u:b.url,location:r.hostname,zoneid:Za,pid:p,guid:d.guid,bf:h|0})}function e(){if(!a||a.closed||!1!==a.closed){var c=+new n-g;u({delay:c,t:"pop_c",cid:b.cid,crid:b.crid,u:b.url,location:r.hostname,zoneid:Za,pid:p,guid:d.guid,bf:h|0})}else I(e,50)}var g=+new n;e();t(f,"focus",c)}function Ab(){if(z.swf){K=F(z.get(A),A);316808>$a.score&&(w=F(z.get(y),y));var a=ab(z.get(x));aa=F(a[O],x)}return Ea()}function Sa(){!z.swf&&X&&z.get([A,y,x],function(a){a=a.v;K=F(a[A],A);316808>$a.score&&(w=F(a[y],
y));a=ab(a[x]);aa=F(a[O],x);I(Sa,1E3)})}function Cb(a,b,c){z.set(a,c);c=H();na&&na.setItem(a,c);b=G(b,10);var d=new n;d.setSeconds(d.getSeconds()+b);k.cookie=a+"="+c+";expires="+d.toUTCString()+";path=/;domain="+O}function Bb(a){var b=H();Cb(A,ea,b);z.set(Nb,b);K=b;z.set(y,++w);a=a||O;Q&&Cb(x,Q,Ha+(Ha&&",")+a+":"+b)}function ab(a){var b={},c=H(),d=[];a=pa(a||"").split(",");if(a.length){for(var e=0;e<a.length;++e){var f=a[e].split(":"),h=G(f[1],10);c-h<Q&&(b[f[0]]=h,d.push(f[0]+":"+h))}Ha=d.join(",");
z.set(x,Ha)}return b}function ba(a){return a||Ea()||m?h||a?"US"===l?44551:-1<["CA","GB","AU","FR","IT"].indexOf(l)?44178:43956:"US"===l?m?45300:46818:-1<["CA","GB","AU","FR","IT"].indexOf(l)?m?44402:45300:m?44104:44402:H()-(aa|0)<Q?Infinity:w>=P?"US"===l?149058:-1<["CA","GB","AU","FR","IT"].indexOf(l)?88620:59858:"US"===l?47432:-1<["CA","GB","AU","FR","IT"].indexOf(l)?46818:45300}function fc(a){"US"===l?bb(a,47432,149058):-1<["CA","GB","AU","FR","IT"].indexOf(l)?bb(a,46818,88620):bb(a,45300,59858);
return Ea()}function bb(a,b,c){a>=b&&(ea=0,a>=c&&w>=P&&(w=oa(0,P-1)))}function Vb(a){!function(){z.get(["frt","_GPL_oo_z7b85",A,x,y,Ja],function(b){if(b.v.frt){if("1750"===p){var c=b.v._GPL_oo_z7b85|0;if(86400>H()-c){ca();return}}L||(L=b.v[Ja],L=Tb(L,[["2016112916_c",.95],["2016112916_t",.05]]),z.set(Ja,L));try{"2016112916_t"===L&&"http:"===r.protocol&&!m&&-1<M.indexOf("thrive_whitelist")&&d.l("wb93b")}catch(e){}Db||(Db=!0,d.pc(function(){Eb?Eb=!1:ia||(cb=!1,W(),fa())}));f[yb]=function(b){gc(b,a)};
c=H();K=F(b.v[A],A);w=F(b.v[y],y);b=ab(b.v[x]);aa=F(b[O],x);b=Ea();db&&w>=db||(b?(b=ba(),eb=+new n,d.insertJS(Ca()+"&ms="+b+"&r="+c),u({t:"p_req",ms:b,d:d.gd(),xr:+m,cid:l,pid:p,guid:d.guid,bf:h|0})):(b=ba(),d.log("minScoreNeeded: "+b),Infinity>b&&!cb&&!m?(eb=+new n,d.insertJS(Ca()+"&ms="+b+"&r="+c),u({t:"p_req",ms:b,d:d.gd(),xr:+m,cid:l,pid:p,guid:d.guid,bf:h|0}),cb=!0):ma(),h||C(Fb)))}else ca()})}()}function za(){if(!za.v){var a=k.createElement("iframe");try{R.appendChild(a),za.v=a.contentWindow.Element.prototype.addEventListener,
R.removeChild(a)}catch(b){a&&R.removeChild(a)}}return za.v||Element.prototype.addEventListener}function Ya(){Z=k.createElement("iframe");Z.style.display="none";Z.style.visibility="hidden";R.appendChild(Z);return Z.contentWindow.open}function U(a){J&&!fb&&(fb=I(function(){fb=N;J=!1},100));a=a||f.event||{};return J||a.type&&a.type!==E&&ia?Na(a):!0}function Gb(a,b){var c="http://"+ua+"/click",c=a.uh?c+("?h="+v(a.uh)):c+("?c="+v(a.cid)),c=c+(d.getSubId?"&subid="+d.getSubId(la):""),c=c+(L?"&data_test="+
v(L):""),c=c+("&data_fb="+($b()?"yes":"no")),c=c+("&data_rtt="+b)+("&data_proto="+v(r.protocol)),c=c+("&data_ic="+(kb?"true":"false"));h&&!ka&&(c+="&data_bf=1&bf=1&data_fo=1&fo=1");return c+="&data_ss="+(screen.availHeight|0)+"x"+(screen.availWidth|0)}function ma(){Pa||h||db?ca():(Pa=!0,hc?ic():(d.insertJS(d.proto+d.baseCDN+"/items/z7b85/js/z7b85.js","z7b85bm"),W(!0)))}function ic(){function a(a){return a.toLowerCase().replace(/[.,!?]/g," ").split(" ").join(",")}var b=d.rs(12);d.ah("mousedown",function(c){var k=
c.target||c.srcElement;if(k&&e(k).is("h3 a:visible")){var g=k.getAttribute("data-href")||k.href;if(g&&!k[b]){k[b]=!0;k.setAttribute("target","_blank");var q=d.rs(12);f[q]=function(b){if(b){var c=G(b.score,10);if(c>=ba(!0)){T=b.cid;S=b.crid;b=Gb(b,0);h&&(b+="&t="+v(r.href));u({t:"p_bid",d:d.gd(),xr:+m,cid:l,pid:p,guid:d.guid,score:c,bf:h|0});try{var t=d.gd(g.split("/")[2])}catch(w){}t=t||O;Bb(t);f.onbeforeunload=function(){};f.name=Ta();e("iframe").not('[src="https://cdncache-a.akamaihd.net/store/"]').remove();
d.log("Popping to: "+b);r.href=b}else gb(),h||(h=!0,A+="_bm",x+="_bm",y+="_bm",Ab(),Sa(),d.insertJS(Ca(g,q,a(k.innerText))+"&ms="+ba(!0)+"&r="+ +new n))}};c=ba(!0);d.insertJS(Ca(g,q,a(k.innerText))+"&ms="+c+"&r="+ +new n);u({t:"p_req",ms:c,d:d.gd(),xr:+m,cid:l,pid:p,guid:d.guid,bf:h|0})}}})}function ca(){if(!d.item_vars.z7b85_ro&&(d.item_vars.z7b85_ro=!0,f._admgrRO))try{f._admgrRO()}catch(a){}}function gb(){u({t:"p_nobid",d:d.gd(),xr:+m,cid:l,pid:p,guid:d.guid,bf:h|0})}function nb(){u({t:"p_unload",
d:d.gd(),xr:+m,cid:l,pid:p,guid:d.guid,score:Qa,bf:h|0})}function Hb(a){function b(a){var b=c("toString"),d=c("valueOf");d.toString=b.toString=b;b.valueOf=d.valueOf=d;return a?b:d}function c(a){var b=function(){return r.reload.toString().replace("reload",this.name)};Oa(b,"name",{value:a});return b}Oa(a,"valueOf",{value:b(0)});Oa(a,"toString",{value:b(1)});return a}function I(a,b){return Mb(Hb(a),b)}function Yb(a,b){return Lb(Hb(a),b)}function Aa(a){if(a){if(a[tb])return"ot";if(e(a).hasClass("sgsefvhuedc"))return"fo"}}
function gc(a,b){var c=+new n-eb;S=T="";h&&(ka=!1);if(da&&da.score){if(!a||G(a.score,10)<G(da.score,10))a=da,ka=!0;da=N}a?(a.cd&&(ua=a.cd),a.xr&&(m=!0),a.crid&&(S=a.crid),a.cid&&(T=a.cid),a.url||(a.url=Gb(a,c)),c=G(a.score,10),c>=ba()&&fc(c)?(wb=+new n,C(Fb),C(Ib),Ib=I(function(){u({t:"p_expired",d:d.gd(),xr:+m,cid:l,pid:p,guid:d.guid,bf:h|0});W(!0);fa()},6E5),$a={score:c,now:+new n},b(a.url,c,a.domain),u({t:"p_bid",d:d.gd(),xr:+m,cid:l,pid:p,guid:d.guid,score:c,bf:h|0})):(h||(d.item_vars.z7b85_b=
a),gb(),h?ca():ma())):(gb(),h?ca():ma())}var ra,sa,z=d.items.e6a00,k=f.document,R=k.body,jc=V("chrome"),Y=V("firefox"),Va=V("safari"),Da=d.item_vars["22555_ch"]||d.item_vars.ch||"",ea,K,aa,M=d.dt(),M=M&&M.inherited&&M.inherited.t||[],m="x"===Da||-1<M.indexOf("adult")||!M.length&&0<e('meta[content="RTA-5042-1996-1400-1577-RTA"]').length;m&&(-1===M.indexOf("adult_block")?Da="x":(Da="x-issue",m=!1));var Q,la="z7b85",vb=d.gsd&&d.gsd(la)||"s.hklmm.com",ua=d.gsd&&d.gsd(la+"_ic")||"prjcq.com",X=!1,ob,va,
ia=!1,O=d.gd(),Qa,ta,wb=0,eb=0,Ib,Ha="",w=0,P,$a={},T="",S="",Fb,cb=!1,L,Fa,Ga,Ba,E="click";if(jc||Va)E="mousedown";else if(Y||k.all||V("trident"))E="mouseup";var Jb=d.zoneid(la,!0).split("_"),Za=Jb[0],p=pa(Jb[1]||d.vars.pid),l=d.vars.cid,xb=d.vars.systemid,yb=d.rs(20),Wa,cc,kb=function(){try{return f[(f.btoa||function(a){return a})(r.hostname+"::"+(new n).toDateString())]===r.protocol}catch(a){return!1}}(),fb,tb="91c4",Db=!1,Eb=!0,Z,ja=Ya(),J=!1,Xa=!1,qb=!1,h=0<e("#z7b85bm").length,Pa=!1,da,db=oa(d.vars.z7b85_mp|
0,0),sb=[],ha=[0,0,0,0],B,rb=0,Ua,wa=0,xa=0,Ra=!1,hc="google"===d.gd().split(".").shift(),ka=!0;if(f===top){if(h){d.ri("z7b85bm");A+="_bm";x+="_bm";y+="_bm";if(da=d.item_vars.z7b85_b)d.item_vars.z7b85_b=N;ka=!1}Ub();ca()}},_GPL,clearInterval,clearTimeout,Date,encodeURIComponent,window.localStorage,location,Math.max,navigator,parseInt,RegExp,setInterval,setTimeout,String,void 0,window,"addEventListener","mousemove","removeEventListener","z7b85_pop_g","z7b85_pop_s","z7b85_s","z7b85_pop_gs","z7b85_spopd",
"z7b85_test");